apiVersion: v1
kind: ServiceAccount
metadata:
  name: rental-external-secrets
  namespace: rental
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::664418980347:role/rentalapp-prod-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: rental-aws-secrets
  namespace: rental
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: rental-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rental-api-secrets
  namespace: rental
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rental-aws-secrets
    kind: SecretStore
  target:
    name: rental-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /rentalapp/eks-prod/mongodb_uri
    - secretKey: SESSION_SECRET
      remoteRef:
        key: /rentalapp/eks-prod/session_secret
    - secretKey: JWT_SECRET
      remoteRef:
        key: /rentalapp/eks-prod/jwt_secret
