apiVersion: v1
kind: ServiceAccount
metadata:
  name: rental-api
  namespace: rental
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rental-client
  namespace: rental
automountServiceAccountToken: false