apiVersion: v1
kind: ConfigMap
metadata:
  name: rental-api-config
  namespace: rental
data:
  CLIENT_URL: "http://rental.local:8080"
  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_SAME_SITE: "lax"
